<?php

namespace Modules\PermissionRoleManager\Services;

use Illuminate\Routing\Route;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Route as RouteFacade;
use Illuminate\Support\Str;
use Modules\PermissionRoleManager\Models\PermissionPermission;
use Modules\PermissionRoleManager\Models\PermissionRole;

class RouteAccessDiscoveryService
{
    public function routes(): Collection
    {
        return collect(RouteFacade::getRoutes())
            ->map(fn(Route $route) => $this->routePayload($route))
            ->filter()
            ->filter(fn(array $route) => $this->hasAuthMiddleware($route['middleware']) || $route['is_backoffice_area'])
            ->sortBy([['module', 'asc'], ['uri', 'asc']])
            ->values();
    }

    public function groupedRoutes(): Collection
    {
        return $this->routes()
            ->groupBy('module')
            ->map(fn(Collection $routes, string $module) => [
                'module' => $module,
                'routes' => $routes->values(),
                'permissions_total' => PermissionPermission::whereIn('key', $routes->pluck('permission_key'))->count(),
            ])
            ->sortKeys();
    }

    public function syncPermissions(?array $modules = null): array
    {
        $created = 0;
        $updated = 0;
        $routes = $this->routesForModules($modules);

        foreach ($routes as $route) {
            $permission = PermissionPermission::withTrashed()->where('key', $route['permission_key'])->first();
            $payload = [
                'key' => $route['permission_key'],
                'label' => $route['label'],
                'module' => $route['module'],
                'group' => 'Routes',
                'risk' => $this->riskForMethods($route['methods']),
                'description' => $route['description'],
                'is_system' => true,
                'is_active' => true,
            ];

            if ($permission) {
                if ($permission->trashed()) {
                    $permission->restore();
                }
                $permission->fill($payload)->save();
                $updated++;
            } else {
                PermissionPermission::create($payload);
                $created++;
            }
        }

        return compact('created', 'updated');
    }

    public function autoGeneratedProfilesCount(): int
    {
        return PermissionRole::where('is_system', true)
            ->where('slug', 'like', 'route-access-%')
            ->count();
    }

    public function archiveAutoGeneratedProfiles(): int
    {
        $roles = PermissionRole::where('is_system', true)
            ->where('slug', 'like', 'route-access-%')
            ->get();

        foreach ($roles as $role) {
            $role->permissions()->detach();
            $role->delete();
        }

        return $roles->count();
    }

    private function routesForModules(?array $modules = null): Collection
    {
        $routes = $this->routes();

        if (!$modules) {
            return $routes;
        }

        return $routes->whereIn('module', $modules)->values();
    }

    private function routePayload(Route $route): ?array
    {
        $controller = $route->getActionName();
        $module = $this->moduleFromController($controller);

        if (!$module) {
            return null;
        }

        $methods = array_values(array_diff($route->methods(), ['HEAD']));
        $name = $route->getName();
        $uri = $route->uri();

        return [
            'module' => $module,
            'name' => $name,
            'uri' => $uri,
            'methods' => $methods,
            'middleware' => $route->gatherMiddleware(),
            'controller' => $controller,
            'is_backoffice_area' => $this->isBackofficeAreaController($controller),
            'permission_key' => $this->permissionKey($route, $methods),
            'label' => $name ? 'Route ' . $name : implode('|', $methods) . ' ' . $uri,
            'description' => implode('|', $methods) . ' /' . $uri . ' -> ' . $controller,
        ];
    }

    private function moduleFromController(string $controller): ?string
    {
        if (str_starts_with($controller, 'Modules\\')) {
            return explode('\\', $controller)[1] ?? null;
        }

        if ($this->isBackofficeAreaController($controller)) {
            return 'BackOfficeAreas';
        }

        return null;
    }

    private function isBackofficeAreaController(string $controller): bool
    {
        return str_starts_with($controller, 'App\\Http\\Controllers\\Areas\\');
    }

    private function hasAuthMiddleware(array $middleware): bool
    {
        foreach ($middleware as $item) {
            if ($item === 'auth' || str_starts_with((string) $item, 'auth:')) {
                return true;
            }
        }

        return false;
    }

    private function permissionKey(Route $route, array $methods): string
    {
        if ($route->getName()) {
            return 'route.' . $route->getName();
        }

        return 'route.' . Str::slug(implode('_', $methods) . '_' . $route->uri(), '.');
    }

    private function riskForMethods(array $methods): string
    {
        if (array_intersect($methods, ['DELETE'])) {
            return 'critical';
        }

        if (array_intersect($methods, ['POST', 'PUT', 'PATCH'])) {
            return 'high';
        }

        return 'medium';
    }
}
