<?php

namespace Modules\PermissionRoleManager\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Modules\PermissionRoleManager\Services\PermissionAuditService;
use Modules\PermissionRoleManager\Services\RouteAccessDiscoveryService;

class PermissionRouteAccessController extends Controller
{
    public function index(RouteAccessDiscoveryService $routeAccess)
    {
        return $this->view('permission-role-manager::route-access.index', [
            'groups' => $routeAccess->groupedRoutes(),
            'autoProfilesCount' => $routeAccess->autoGeneratedProfilesCount(),
        ]);
    }

    public function syncPermissions(Request $request, RouteAccessDiscoveryService $routeAccess, PermissionAuditService $audit)
    {
        $modules = $this->selectedModules($request);
        $result = $routeAccess->syncPermissions($modules);

        $audit->log('route_access.permissions.synced', 'route_access', null, null, [
            'modules' => $modules,
            'result' => $result,
        ]);

        return back()->with('success', "Permissions de rotas sincronizadas: {$result['created']} criadas, {$result['updated']} atualizadas.");
    }

    public function archiveAutoProfiles(RouteAccessDiscoveryService $routeAccess, PermissionAuditService $audit)
    {
        $archived = $routeAccess->archiveAutoGeneratedProfiles();

        $audit->log('route_access.auto_profiles.archived', 'route_access', null, null, [
            'archived' => $archived,
        ]);

        return back()->with('success', "{$archived} perfis automaticos arquivados.");
    }

    private function selectedModules(Request $request): ?array
    {
        $modules = array_values(array_filter((array) $request->input('modules', [])));

        return $modules === [] ? null : $modules;
    }
}
