<?php

return [
    'optimize_clear' => [
        'section' => 'cache',
        'label' => 'Optimize Clear',
        'description' => 'Limpa cache geral, config, routes, views e ficheiros otimizados.',
        'icon' => 'fa-solid fa-broom',
        'command' => 'optimize:clear',
        'params' => [],
        'risk' => 'safe',
        'external' => true,
        'requires_confirmation' => false,
    ],
    'cache_clear' => [
        'section' => 'cache',
        'label' => 'Cache Clear',
        'description' => 'Limpa a cache da aplicação.',
        'icon' => 'fa-solid fa-database',
        'command' => 'cache:clear',
        'params' => [],
        'risk' => 'safe',
        'external' => true,
        'requires_confirmation' => false,
    ],
    'config_clear' => [
        'section' => 'cache',
        'label' => 'Config Clear',
        'description' => 'Limpa a cache de configuração.',
        'icon' => 'fa-solid fa-sliders',
        'command' => 'config:clear',
        'params' => [],
        'risk' => 'safe',
        'external' => true,
        'requires_confirmation' => false,
    ],
    'route_clear' => [
        'section' => 'cache',
        'label' => 'Route Clear',
        'description' => 'Limpa a cache de rotas.',
        'icon' => 'fa-solid fa-route',
        'command' => 'route:clear',
        'params' => [],
        'risk' => 'safe',
        'external' => true,
        'requires_confirmation' => false,
    ],
    'view_clear' => [
        'section' => 'cache',
        'label' => 'View Clear',
        'description' => 'Limpa a cache das views Blade.',
        'icon' => 'fa-solid fa-eye',
        'command' => 'view:clear',
        'params' => [],
        'risk' => 'safe',
        'external' => true,
        'requires_confirmation' => false,
    ],
    'config_cache' => [
        'section' => 'cache',
        'label' => 'Config Cache',
        'description' => 'Recria a cache de configuração.',
        'icon' => 'fa-solid fa-gears',
        'command' => 'config:cache',
        'params' => [],
        'risk' => 'medium',
        'external' => false,
        'requires_confirmation' => true,
    ],
    'route_cache' => [
        'section' => 'cache',
        'label' => 'Route Cache',
        'description' => 'Recria a cache de rotas.',
        'icon' => 'fa-solid fa-diagram-project',
        'command' => 'route:cache',
        'params' => [],
        'risk' => 'medium',
        'external' => false,
        'requires_confirmation' => true,
    ],
    'view_cache' => [
        'section' => 'cache',
        'label' => 'View Cache',
        'description' => 'Compila e guarda cache das views.',
        'icon' => 'fa-solid fa-layer-group',
        'command' => 'view:cache',
        'params' => [],
        'risk' => 'medium',
        'external' => false,
        'requires_confirmation' => true,
    ],
    'migrate_status' => [
        'section' => 'database',
        'label' => 'Migrate Status',
        'description' => 'Mostra o estado das migrations.',
        'icon' => 'fa-solid fa-list-check',
        'command' => 'migrate:status',
        'params' => [],
        'risk' => 'safe',
        'external' => false,
        'requires_confirmation' => false,
    ],
    'migrate_force' => [
        'section' => 'database',
        'label' => 'Run Migrations',
        'description' => 'Executa migrations em produção com --force.',
        'icon' => 'fa-solid fa-database',
        'command' => 'migrate',
        'params' => ['--force' => true],
        'risk' => 'danger',
        'external' => false,
        'requires_confirmation' => true,
    ],
    'queue_restart' => [
        'section' => 'queue',
        'label' => 'Queue Restart',
        'description' => 'Reinicia os workers de queue.',
        'icon' => 'fa-solid fa-rotate',
        'command' => 'queue:restart',
        'params' => [],
        'risk' => 'safe',
        'external' => true,
        'requires_confirmation' => false,
    ],
    'queue_failed' => [
        'section' => 'queue',
        'label' => 'Failed Jobs',
        'description' => 'Lista jobs falhados.',
        'icon' => 'fa-solid fa-triangle-exclamation',
        'command' => 'queue:failed',
        'params' => [],
        'risk' => 'safe',
        'external' => false,
        'requires_confirmation' => false,
    ],
    'storage_link' => [
        'section' => 'storage',
        'label' => 'Storage Link',
        'description' => 'Cria o symbolic link public/storage.',
        'icon' => 'fa-solid fa-link',
        'command' => 'storage:link',
        'params' => [],
        'risk' => 'medium',
        'external' => false,
        'requires_confirmation' => true,
    ],
    'diagnostics_info' => [
        'section' => 'diagnostics',
        'label' => 'System Info',
        'description' => 'Mostra informação rápida do ambiente.',
        'icon' => 'fa-solid fa-circle-info',
        'type' => 'custom',
        'handler' => 'system_info',
        'risk' => 'safe',
        'external' => false,
        'requires_confirmation' => false,
    ],
    'diagnostics_writable' => [
        'section' => 'diagnostics',
        'label' => 'Writable Paths',
        'description' => 'Verifica permissões de storage e bootstrap/cache.',
        'icon' => 'fa-solid fa-shield-halved',
        'type' => 'custom',
        'handler' => 'writable_paths',
        'risk' => 'safe',
        'external' => false,
        'requires_confirmation' => false,
    ],
];
