<?php

return [
    'structural' => [
        'label' => 'Structural Module',
        'description' => 'Base profile for standard WebTools Manager modules.',
        'required' => [
            'module_json',
            'service_provider',
            'web_routes',
            'controllers',
            'views',
            'config',
            'translations',
            'breadcrumbs',
            'actions',
        ],
        'recommended' => [
            'models',
            'migrations',
            'permissions',
            'page_titles',
            'diagnostics',
            'seeders',
        ],
        'optional' => [
            'api_routes',
            'jobs',
            'events',
            'commands',
            'exports',
            'imports',
            'webhooks',
            'tests',
        ],
    ],

    'library' => [
        'label' => 'Library Module',
        'description' => 'Profile for shared service/contract modules without BO pages.',
        'required' => [
            'module_json',
            'service_provider',
        ],
        'recommended' => [],
        'optional' => [
            'config',
            'permissions',
            'translations',
            'documentation',
            'models',
            'migrations',
            'seeders',
            'jobs',
            'tests',
        ],
    ],

    'validator' => [
        'label' => 'Validator Module',
        'description' => 'Profile for compliance validators and bridge modules with a small UI surface.',
        'required' => [
            'module_json',
            'service_provider',
            'web_routes',
            'controllers',
            'views',
            'config',
            'translations',
        ],
        'recommended' => [],
        'optional' => [
            'permissions',
            'page_titles',
            'breadcrumbs',
            'actions',
            'diagnostics',
            'seeders',
            'tests',
        ],
    ],

    'operational' => [
        'label' => 'Operational Module',
        'description' => 'Profile for modules that control operational business workflows.',
        'required' => [
            'module_json',
            'service_provider',
            'web_routes',
            'controllers',
            'models',
            'views',
            'migrations',
            'config',
            'translations',
            'breadcrumbs',
            'actions',
        ],
        'recommended' => [
            'permissions',
            'diagnostics',
            'audit_logs',
            'notifications',
            'seeders',
            'exports',
        ],
        'optional' => [
            'api_routes',
            'jobs',
            'events',
            'commands',
            'scheduler',
            'webhooks',
            'tests',
        ],
    ],

    'saas_candidate' => [
        'label' => 'SaaS Candidate',
        'description' => 'Profile for modules that may later be extracted into public products.',
        'required' => [
            'module_json',
            'service_provider',
            'web_routes',
            'controllers',
            'models',
            'views',
            'migrations',
            'config',
            'translations',
        ],
        'recommended' => [
            'api_routes',
            'permissions',
            'jobs',
            'events',
            'notifications',
            'tests',
            'diagnostics',
        ],
        'optional' => [
            'billing',
            'multi_tenant',
            'public_assets',
            'webhooks',
            'sdk',
            'documentation',
        ],
    ],
];
