<?php

namespace Modules\DataExportCenter\Services;

use Illuminate\Support\Str;

class ExportSchemaBuilder
{
    public function __construct(
        private readonly ExportDependencyResolver $resolver
    ) {
    }

    public function build(string $rootClass): array
    {
        $graph = $this->resolver->resolve($rootClass);

        $headers = [];
        $fields = [];
        $nodeFields = [];
        $warnings = [];
        $filters = [];

        foreach ($this->orderedNodes($graph['nodes']) as $node) {
            $class = $node['class'];
            $classFields = $this->fieldsForClass($class);

            foreach ($classFields as $fieldKey => $definition) {
                if (($definition['exportable'] ?? true) === false) {
                    continue;
                }

                $csvKey = $this->csvKeyFor($node, (string) $fieldKey);

                if (isset($fields[$csvKey])) {
                    $warnings[] = "Duplicated export field [{$csvKey}] generated by [{$class}].";
                    continue;
                }

                $definition = array_merge([
                    'label' => $fieldKey,
                    'required' => false,
                    'type' => 'string',
                    'example' => '',
                    'column' => $fieldKey,
                    'select' => null,
                    'exportable' => true,
                ], $definition);

                $definition['csv_key'] = $csvKey;
                $definition['field_key'] = (string) $fieldKey;
                $definition['source_id'] = $node['id'];
                $definition['source_alias'] = $node['alias'];
                $definition['source_class'] = $class;
                $definition['source_label'] = $node['label'];
                $definition['is_dependency'] = ! $node['is_root'];

                $headers[] = $csvKey;
                $fields[$csvKey] = $definition;
                $nodeFields[$node['id']][(string) $fieldKey] = $definition;
            }

            foreach ($this->filtersForClass($class) as $filterKey => $filterDefinition) {
                $filterCsvKey = $this->csvKeyFor($node, (string) $filterKey);
                $filters[$filterCsvKey] = array_merge([
                    'label' => $filterKey,
                    'type' => 'string',
                    'operator' => '=',
                    'column' => $filterKey,
                ], $filterDefinition, [
                    'key' => $filterCsvKey,
                    'source_id' => $node['id'],
                    'source_alias' => $node['alias'],
                ]);
            }
        }

        return [
            'graph' => $graph,
            'headers' => $headers,
            'fields' => $fields,
            'filters' => $filters,
            'node_fields' => $nodeFields,
            'warnings' => $warnings,
        ];
    }

    public function csvKeyFor(array $node, string $fieldKey): string
    {
        if ($node['is_root'] || ($node['preserve_keys'] ?? false)) {
            return $fieldKey;
        }

        $prefix = $node['prefix'] ?: $node['alias'];

        if (Str::startsWith($fieldKey, $prefix . '_')) {
            return $fieldKey;
        }

        return $prefix . '_' . $fieldKey;
    }

    private function orderedNodes(array $nodes): array
    {
        usort($nodes, function (array $a, array $b) {
            if (($a['is_root'] ?? false) !== ($b['is_root'] ?? false)) {
                return ($a['is_root'] ?? false) ? -1 : 1;
            }

            $levelCompare = (($a['level'] ?? 0) <=> ($b['level'] ?? 0));
            if ($levelCompare !== 0) {
                return $levelCompare;
            }

            return strcmp($a['id'], $b['id']);
        });

        return $nodes;
    }

    private function fieldsForClass(string $class): array
    {
        if (method_exists($class, 'exportFields')) {
            return $class::exportFields();
        }

        if (method_exists($class, 'importFields')) {
            return $class::importFields();
        }

        return [];
    }

    private function filtersForClass(string $class): array
    {
        if (method_exists($class, 'exportFilters')) {
            return $class::exportFilters();
        }

        return [];
    }
}
