<?php

return [
    'stores' => [
        'label' => 'Stores',
        'icon' => 'fa-solid fa-store',
        'description' => 'Import stores/clients and their base commercial identity.',
        'columns' => [
            'name',
            'slug',
            'code',
            'domain',
            'status',
            'metadata',
        ],
        'required' => [
            'name',
            'code',
        ],
        'sample' => [
            'Life-Style',
            'life-style',
            'LS',
            'life-style.pt',
            'active',
            '{}',
        ],
    ],
    'catalogues' => [
        'label' => 'Catalogues',
        'icon' => 'fa-solid fa-book-open',
        'description' => 'Import catalogues and associate them with a store by store_code.',
        'columns' => [
            'store_code',
            'name',
            'slug',
            'description',
            'catalogue_type',
            'visibility',
            'show_prices',
            'show_promotions',
            'price_mode',
            'status',
            'metadata',
        ],
        'required' => [
            'store_code',
            'name',
            'slug',
        ],
        'sample' => [
            'LS',
            'Industrial 2026',
            'industrial-2026',
            'B2B visual catalogue',
            'mixed',
            'public',
            '1',
            '1',
            'visible',
            'draft',
            '{}',
        ],
    ],
    'products' => [
        'label' => 'Products',
        'icon' => 'fa-solid fa-boxes-stacked',
        'description' => 'Import products, commercial data and product resources. Image/resource URLs are downloaded and registered in wc_resources during confirmation.',
        'columns' => [
            'store_code',
            'catalogue_slug',
            'external_id',
            'external_source',
            'reference',
            'sku',
            'ean13',
            'name',
            'slug',
            'short_description',
            'description',
            'brand',
            'category',
            'price',
            'currency',
            'stock',
            'status',
            'image_urls',
            'gallery_image_urls',
            'manual_urls',
            'datasheet_urls',
            'video_urls',
            'audio_urls',
            'model_3d_url',
            'ar_file_url',
            'vr_file_url',
            'tags',
            'metadata',
        ],
        'required' => [
            'store_code',
            'reference',
            'name',
        ],
        'sample' => [
            'LS',
            'industrial-2026',
            '12345',
            'csv',
            'CH-01',
            'CH-01',
            '5600000000000',
            'Industrial Chair',
            'industrial-chair',
            'Short description',
            'Full description',
            'LSG Furniture',
            'Chairs',
            '129.90',
            'EUR',
            '25',
            'active',
            'https://example.com/main.jpg',
            'https://example.com/gallery-1.jpg|https://example.com/gallery-2.jpg',
            'https://example.com/manual.pdf',
            'https://example.com/datasheet.pdf',
            'https://example.com/demo.mp4',
            'https://example.com/audio.mp3',
            'https://example.com/model.glb',
            'https://example.com/model.usdz',
            '',
            'chair|industrial',
            '{}',
        ],
    ],
    'resources' => [
        'label' => 'Resources',
        'icon' => 'fa-solid fa-photo-film',
        'description' => 'Import images, documents, video, audio, 3D, AR/VR and external links for stores, catalogues, products, themes or environments.',
        'columns' => [
            'store_code',
            'catalogue_slug',
            'product_reference',
            'product_sku',
            'product_external_id',
            'id_product',
            'resource_owner_type',
            'resource_owner_key',
            'resource_type',
            'title',
            'description',
            'source_type',
            'source_url',
            'is_main',
            'sort_order',
            'status',
            'metadata',
        ],
        'required' => [
            'store_code',
            'resource_type',
            'source_url',
        ],
        'sample' => [
            'LS',
            'industrial-2026',
            'CH-01',
            '',
            '',
            '',
            'product',
            'CH-01',
            'image',
            'Main image',
            '',
            'external_url',
            'https://example.com/image.jpg',
            '1',
            '1',
            'active',
            '{}',
        ],
    ],
    'prices' => [
        'label' => 'Prices',
        'icon' => 'fa-solid fa-tags',
        'description' => 'Import product prices, sale prices, tax settings and validity windows.',
        'columns' => [
            'store_code',
            'product_reference',
            'price_type',
            'currency',
            'regular_price',
            'sale_price',
            'tax_included',
            'tax_rate',
            'valid_from',
            'valid_until',
            'status',
            'metadata',
        ],
        'required' => [
            'store_code',
            'product_reference',
            'regular_price',
            'currency',
        ],
        'sample' => [
            'LS',
            'CH-01',
            'standard',
            'EUR',
            '129.90',
            '99.90',
            '1',
            '23',
            '',
            '',
            'active',
            '{}',
        ],
    ],
    'promotions' => [
        'label' => 'Promotions',
        'icon' => 'fa-solid fa-bullhorn',
        'description' => 'Import promotion headers. Product assignment can be done later through promotion_products.',
        'columns' => [
            'store_code',
            'catalogue_slug',
            'name',
            'slug',
            'description',
            'promotion_type',
            'badge_label',
            'discount_type',
            'discount_value',
            'starts_at',
            'ends_at',
            'status',
            'metadata',
        ],
        'required' => [
            'store_code',
            'name',
            'slug',
        ],
        'sample' => [
            'LS',
            'industrial-2026',
            'Spring Campaign',
            'spring-campaign',
            'Campaign description',
            'campaign',
            'Promo',
            'percentage',
            '20',
            '2026-05-01',
            '2026-05-31',
            'active',
            '{}',
        ],
    ],
    'promotion_products' => [
        'label' => 'Promotion Products',
        'icon' => 'fa-solid fa-percent',
        'description' => 'Import products into existing promotions.',
        'columns' => [
            'store_code',
            'promotion_slug',
            'product_reference',
            'custom_badge_label',
            'custom_sale_price',
            'sort_order',
            'status',
            'metadata',
        ],
        'required' => [
            'store_code',
            'promotion_slug',
            'product_reference',
        ],
        'sample' => [
            'LS',
            'spring-campaign',
            'CH-01',
            'Best Deal',
            '99.90',
            '1',
            'active',
            '{}',
        ],
    ],
    'themes' => [
        'label' => 'Themes',
        'icon' => 'fa-solid fa-palette',
        'description' => 'Import store visual themes: colors, fonts, button/card styles and CSS.',
        'columns' => [
            'store_code',
            'name',
            'slug',
            'is_default',
            'font_family',
            'heading_font_family',
            'primary_color',
            'secondary_color',
            'accent_color',
            'background_color',
            'text_color',
            'button_style',
            'card_style',
            'border_radius',
            'custom_css',
            'status',
            'metadata',
        ],
        'required' => [
            'store_code',
            'name',
            'slug',
        ],
        'sample' => [
            'LS',
            'LSG Premium',
            'lsg-premium',
            '1',
            'Inter',
            'Inter',
            '#ffffff',
            '#d4af37',
            '#111827',
            '#f8fafc',
            '#111827',
            'rounded',
            'premium',
            '5px',
            '',
            'active',
            '{}',
        ],
    ],
    'environments' => [
        'label' => 'Environments',
        'icon' => 'fa-solid fa-vr-cardboard',
        'description' => 'Import 3D/VR environments, backgrounds, lighting and AR/VR scene configuration.',
        'columns' => [
            'store_code',
            'name',
            'slug',
            'is_default',
            'environment_type',
            'background_type',
            'background_color',
            'lighting_preset',
            'camera_preset',
            'vr_scene_config',
            'ar_scene_config',
            'status',
            'metadata',
        ],
        'required' => [
            'store_code',
            'name',
            'slug',
        ],
        'sample' => [
            'LS',
            'Studio Showroom',
            'studio-showroom',
            '1',
            'showroom',
            'color',
            '#f8fafc',
            'studio_soft',
            'product_front',
            '{}',
            '{}',
            'active',
            '{}',
        ],
    ],
    'settings' => [
        'label' => 'Settings',
        'icon' => 'fa-solid fa-sliders',
        'description' => 'Import key/value settings globally or per store.',
        'columns' => [
            'store_code',
            'group',
            'key',
            'value',
            'type',
            'metadata',
        ],
        'required' => [
            'key',
            'value',
        ],
        'sample' => [
            'LS',
            'viewer',
            'default_camera',
            'front',
            'string',
            '{}',
        ],
    ],
];
