CREATE TABLE IF NOT EXISTS `wt_projects` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'New',
  `priority` INT UNSIGNED NOT NULL DEFAULT 0,
  `id_parent` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  `url` VARCHAR(500) NULL,
  `website` VARCHAR(500) NULL,
  `logo` VARCHAR(1000) NULL,
  `description` TEXT NULL,
  `repository_url` VARCHAR(500) NULL,
  `documentation_url` VARCHAR(500) NULL,
  `staging_url` VARCHAR(500) NULL,
  `production_url` VARCHAR(500) NULL,
  `server_notes` TEXT NULL,
  `deployment_notes` TEXT NULL,
  `business_model` VARCHAR(191) NULL,
  `market_scope` VARCHAR(191) NULL,
  `owner_name` VARCHAR(191) NULL,
  `owner_email` VARCHAR(191) NULL,
  `contact_name` VARCHAR(191) NULL,
  `contact_email` VARCHAR(191) NULL,
  `contact_phone` VARCHAR(50) NULL,
  `primary_color` VARCHAR(20) NULL,
  `secondary_color` VARCHAR(20) NULL,
  `accent_color` VARCHAR(20) NULL,
  `font_family` VARCHAR(120) NULL,
  `brand_notes` TEXT NULL,
  `team_json` LONGTEXT NULL,
  `team_notes` TEXT NULL,
  `structure_notes` TEXT NULL,
  `documentation_notes` TEXT NULL,
  `goals` TEXT NULL,
  `risks` TEXT NULL,
  `next_steps` TEXT NULL,
  `budget_notes` TEXT NULL,
  `start_date` DATE NULL,
  `deadline` DATE NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
