<?php

return [
    'required_directories' => [
        'Config' => 'medium',
        'Http/Controllers' => 'high',
        'Models' => 'medium',
        'Services' => 'medium',
        'Resources/views' => 'high',
        'routes' => 'high',
        'lang/pt' => 'medium',
        'lang/en' => 'medium',
    ],

    'required_files' => [
        'module.json' => 'blocker',
        'routes/web.php' => 'high',
    ],

    'manifest_required_keys' => [
        'name',
        'slug',
        'version',
        'provider',
        'permissions',
    ],

    'safe_root_files' => [
        'module.json',
        'README.md',
        'composer.json',
        'AI_CONSENSUS_RUN.md',
        'blueprint.json',
        'lsg-standard.json',
    ],

    'allowed_root_directories' => [
        'Config',
        'Console',
        'Contracts',
        'Database',
        'DTO',
        'DTOs',
        'Docs',
        'Enums',
        'Entities',
        'Events',
        'Exceptions',
        'Examples',
        'Http',
        'Includes',
        'Inspectors',
        'Jobs',
        'Listeners',
        'Models',
        'Microservices',
        'Policies',
        'Providers',
        'Repositories',
        'Resources',
        'README',
        'Services',
        'Support',
        'Validators',
        'Routes',
        'config',
        'routes',
        'lang',
        'docs',
        'Tests',
        'Tasks',
        'Traits',
        'examples',
        'tests',
    ],

    'permission_prefix' => 'permission_',
    'max_mysql_identifier_length' => 64,
];
