<div class="pm-tabs">
    <button type="button" class="pm-tab is-active" data-tab="base">Base</button>
    <button type="button" class="pm-tab" data-tab="business">Business</button>
    <button type="button" class="pm-tab" data-tab="branding">Branding</button>
    <button type="button" class="pm-tab" data-tab="contacts">Contacts</button>
    <button type="button" class="pm-tab" data-tab="technical">Technical</button>
    <button type="button" class="pm-tab" data-tab="planning">Planning</button>
</div>

<div class="pm-tab-panel is-active" data-panel="base">
    <div class="pm-grid pm-grid-2">
        <div class="pm-info-box">
            <div class="mb-3"><label>Nome</label><input type="text" name="name" class="form-control" value="{{ old('name', $project->name ?? '') }}" required></div>
            <div class="mb-3"><label>Slug</label><input type="text" name="slug" class="form-control" value="{{ old('slug', $project->slug ?? '') }}"></div>
            <div class="mb-3"><label>Projeto pai</label><select name="id_parent" class="form-control"><option value="0">Projeto pai</option>@foreach($projects as $parentProject)<option value="{{ $parentProject->id }}" @selected((int) old('id_parent', request('id_parent', $project->id_parent ?? 0)) === (int) $parentProject->id)>{{ $parentProject->name }}</option>@endforeach</select></div>
            <div class="mb-3"><label>Status</label><select name="status" class="form-control">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $project->status ?? 'New') === $status)>{{ $status }}</option>@endforeach</select></div>
            <div class="mb-3"><label>Prioridade</label><input type="number" name="priority" class="form-control" min="0" value="{{ old('priority', $project->priority ?? 0) }}"></div>
        </div>
        <div class="pm-info-box"><div class="mb-3"><label>Descrição</label><textarea name="description" class="form-control" rows="10">{{ old('description', $project->description ?? '') }}</textarea></div></div>
    </div>
</div>

<div class="pm-tab-panel" data-panel="business"><div class="pm-grid pm-grid-2"><div class="pm-info-box"><div class="mb-3"><label>Business model</label><input type="text" name="business_model" class="form-control" value="{{ old('business_model', $project->business_model ?? '') }}"></div><div class="mb-3"><label>Market scope</label><input type="text" name="market_scope" class="form-control" value="{{ old('market_scope', $project->market_scope ?? '') }}"></div><div class="mb-3"><label>Owner name</label><input type="text" name="owner_name" class="form-control" value="{{ old('owner_name', $project->owner_name ?? '') }}"></div><div class="mb-3"><label>Owner email</label><input type="text" name="owner_email" class="form-control" value="{{ old('owner_email', $project->owner_email ?? '') }}"></div></div><div class="pm-info-box"><div class="mb-3"><label>Budget notes</label><textarea name="budget_notes" class="form-control" rows="4">{{ old('budget_notes', $project->budget_notes ?? '') }}</textarea></div><div class="mb-3"><label>Goals</label><textarea name="goals" class="form-control" rows="3">{{ old('goals', $project->goals ?? '') }}</textarea></div><div class="mb-3"><label>Risks</label><textarea name="risks" class="form-control" rows="3">{{ old('risks', $project->risks ?? '') }}</textarea></div><div class="mb-3"><label>Next steps</label><textarea name="next_steps" class="form-control" rows="3">{{ old('next_steps', $project->next_steps ?? '') }}</textarea></div></div></div></div>

<div class="pm-tab-panel" data-panel="branding"><div class="pm-grid pm-grid-2"><div class="pm-info-box"><div class="mb-3"><label>Logo URL</label><input type="text" name="logo" class="form-control" value="{{ old('logo', $project->logo ?? '') }}"></div><div class="mb-3"><label>Primary color</label><input type="text" name="primary_color" class="form-control" value="{{ old('primary_color', $project->primary_color ?? '') }}"></div><div class="mb-3"><label>Secondary color</label><input type="text" name="secondary_color" class="form-control" value="{{ old('secondary_color', $project->secondary_color ?? '') }}"></div><div class="mb-3"><label>Accent color</label><input type="text" name="accent_color" class="form-control" value="{{ old('accent_color', $project->accent_color ?? '') }}"></div><div class="mb-3"><label>Font family</label><input type="text" name="font_family" class="form-control" value="{{ old('font_family', $project->font_family ?? '') }}"></div></div><div class="pm-info-box"><div class="mb-3"><label>Brand notes</label><textarea name="brand_notes" class="form-control" rows="8">{{ old('brand_notes', $project->brand_notes ?? '') }}</textarea></div></div></div></div>

<div class="pm-tab-panel" data-panel="contacts"><div class="pm-grid pm-grid-2"><div class="pm-info-box"><div class="mb-3"><label>Contact name</label><input type="text" name="contact_name" class="form-control" value="{{ old('contact_name', $project->contact_name ?? '') }}"></div><div class="mb-3"><label>Contact email</label><input type="text" name="contact_email" class="form-control" value="{{ old('contact_email', $project->contact_email ?? '') }}"></div><div class="mb-3"><label>Contact phone</label><input type="text" name="contact_phone" class="form-control" value="{{ old('contact_phone', $project->contact_phone ?? '') }}"></div><div class="mb-3"><label>Website</label><input type="text" name="website" class="form-control" value="{{ old('website', $project->website ?? '') }}"></div></div><div class="pm-info-box"><div class="mb-3"><label>Team JSON</label><textarea name="team_json" class="form-control" rows="5">{{ old('team_json', $project->team_json ?? '') }}</textarea></div><div class="mb-3"><label>Team notes</label><textarea name="team_notes" class="form-control" rows="5">{{ old('team_notes', $project->team_notes ?? '') }}</textarea></div></div></div></div>

<div class="pm-tab-panel" data-panel="technical"><div class="pm-grid pm-grid-2"><div class="pm-info-box"><div class="mb-3"><label>Main URL</label><input type="text" name="url" class="form-control" value="{{ old('url', $project->url ?? '') }}"></div><div class="mb-3"><label>Repository URL</label><input type="text" name="repository_url" class="form-control" value="{{ old('repository_url', $project->repository_url ?? '') }}"></div><div class="mb-3"><label>Documentation URL</label><input type="text" name="documentation_url" class="form-control" value="{{ old('documentation_url', $project->documentation_url ?? '') }}"></div><div class="mb-3"><label>Staging URL</label><input type="text" name="staging_url" class="form-control" value="{{ old('staging_url', $project->staging_url ?? '') }}"></div><div class="mb-3"><label>Production URL</label><input type="text" name="production_url" class="form-control" value="{{ old('production_url', $project->production_url ?? '') }}"></div></div><div class="pm-info-box"><div class="mb-3"><label>Server notes</label><textarea name="server_notes" class="form-control" rows="5">{{ old('server_notes', $project->server_notes ?? '') }}</textarea></div><div class="mb-3"><label>Deployment notes</label><textarea name="deployment_notes" class="form-control" rows="5">{{ old('deployment_notes', $project->deployment_notes ?? '') }}</textarea></div><div class="mb-3"><label>Structure notes</label><textarea name="structure_notes" class="form-control" rows="4">{{ old('structure_notes', $project->structure_notes ?? '') }}</textarea></div><div class="mb-3"><label>Documentation notes</label><textarea name="documentation_notes" class="form-control" rows="4">{{ old('documentation_notes', $project->documentation_notes ?? '') }}</textarea></div></div></div></div>

<div class="pm-tab-panel" data-panel="planning"><div class="pm-grid pm-grid-2"><div class="pm-info-box"><div class="mb-3"><label>Start date</label><input type="date" name="start_date" class="form-control" value="{{ old('start_date', optional($project->start_date ?? null)->format('Y-m-d')) }}"></div><div class="mb-3"><label>Deadline</label><input type="date" name="deadline" class="form-control" value="{{ old('deadline', optional($project->deadline ?? null)->format('Y-m-d')) }}"></div></div></div></div>

<div class="mt-3 d-flex gap-2">
    <a href="{{ route('project_manager.index') }}" class="btn btn-outline-primary"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
    <button type="submit" class="btn btn-outline-primary"><i class="fa-regular fa-floppy-disk" aria-hidden="true"></i></button>
</div>
