<div class="pm-tabs">
    <button type="button" class="pm-tab is-active" data-tab="base">{{ __('project-manager::project_manager.tabs.base') }}</button>
    <button type="button" class="pm-tab" data-tab="business">{{ __('project-manager::project_manager.tabs.business') }}</button>
    <button type="button" class="pm-tab" data-tab="branding">{{ __('project-manager::project_manager.tabs.branding') }}</button>
    <button type="button" class="pm-tab" data-tab="contacts">{{ __('project-manager::project_manager.tabs.contacts') }}</button>
    <button type="button" class="pm-tab" data-tab="technical">{{ __('project-manager::project_manager.tabs.technical') }}</button>
    <button type="button" class="pm-tab" data-tab="planning">{{ __('project-manager::project_manager.tabs.planning') }}</button>
</div>

<div class="pm-tab-panel is-active" data-panel="base">
    <div class="pm-grid pm-grid-2">
        <div class="pm-info-box">
            <div class="mb-3"><label>{{ __('project-manager::project_manager.fields.name') }}</label><input type="text" name="name" class="form-control" value="{{ old('name', $project->name ?? '') }}" required></div>
            <div class="mb-3"><label>{{ __('project-manager::project_manager.fields.slug') }}</label><input type="text" name="slug" class="form-control" value="{{ old('slug', $project->slug ?? '') }}"></div>
            <div class="mb-3"><label>{{ __('project-manager::project_manager.fields.parent_project') }}</label><select name="id_parent" class="form-control"><option value="0">{{ __('project-manager::project_manager.fields.parent_project_option') }}</option>@foreach($projects as $parentProject)<option value="{{ $parentProject->id }}" @selected((int) old('id_parent', request('id_parent', $project->id_parent ?? 0)) === (int) $parentProject->id)>{{ $parentProject->name }}</option>@endforeach</select></div>
            <div class="mb-3"><label>{{ __('project-manager::project_manager.fields.status') }}</label><select name="status" class="form-control">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $project->status ?? 'New') === $status)>{{ $status }}</option>@endforeach</select></div>
            <div class="mb-3"><label>{{ __('project-manager::project_manager.fields.priority') }}</label><input type="number" name="priority" class="form-control" min="0" value="{{ old('priority', $project->priority ?? 0) }}"></div>
        </div>
        <div class="pm-info-box"><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.description') }}</label><textarea name="description" class="form-control" rows="10">{{ old('description', $project->description ?? '') }}</textarea></div></div>
    </div>
</div>

<div class="pm-tab-panel" data-panel="business"><div class="pm-grid pm-grid-2"><div class="pm-info-box"><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.business_model') }}</label><input type="text" name="business_model" class="form-control" value="{{ old('business_model', $project->business_model ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.market_scope') }}</label><input type="text" name="market_scope" class="form-control" value="{{ old('market_scope', $project->market_scope ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.owner_name') }}</label><input type="text" name="owner_name" class="form-control" value="{{ old('owner_name', $project->owner_name ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.owner_email') }}</label><input type="text" name="owner_email" class="form-control" value="{{ old('owner_email', $project->owner_email ?? '') }}"></div></div><div class="pm-info-box"><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.budget_notes') }}</label><textarea name="budget_notes" class="form-control" rows="4">{{ old('budget_notes', $project->budget_notes ?? '') }}</textarea></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.goals') }}</label><textarea name="goals" class="form-control" rows="3">{{ old('goals', $project->goals ?? '') }}</textarea></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.risks') }}</label><textarea name="risks" class="form-control" rows="3">{{ old('risks', $project->risks ?? '') }}</textarea></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.next_steps') }}</label><textarea name="next_steps" class="form-control" rows="3">{{ old('next_steps', $project->next_steps ?? '') }}</textarea></div></div></div></div>

<div class="pm-tab-panel" data-panel="branding"><div class="pm-grid pm-grid-2"><div class="pm-info-box"><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.logo_url') }}</label><input type="text" name="logo" class="form-control" value="{{ old('logo', $project->logo ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.primary_color') }}</label><input type="text" name="primary_color" class="form-control" value="{{ old('primary_color', $project->primary_color ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.secondary_color') }}</label><input type="text" name="secondary_color" class="form-control" value="{{ old('secondary_color', $project->secondary_color ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.accent_color') }}</label><input type="text" name="accent_color" class="form-control" value="{{ old('accent_color', $project->accent_color ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.font_family') }}</label><input type="text" name="font_family" class="form-control" value="{{ old('font_family', $project->font_family ?? '') }}"></div></div><div class="pm-info-box"><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.brand_notes') }}</label><textarea name="brand_notes" class="form-control" rows="8">{{ old('brand_notes', $project->brand_notes ?? '') }}</textarea></div></div></div></div>

<div class="pm-tab-panel" data-panel="contacts"><div class="pm-grid pm-grid-2"><div class="pm-info-box"><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.contact_name') }}</label><input type="text" name="contact_name" class="form-control" value="{{ old('contact_name', $project->contact_name ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.contact_email') }}</label><input type="text" name="contact_email" class="form-control" value="{{ old('contact_email', $project->contact_email ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.contact_phone') }}</label><input type="text" name="contact_phone" class="form-control" value="{{ old('contact_phone', $project->contact_phone ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.website') }}</label><input type="text" name="website" class="form-control" value="{{ old('website', $project->website ?? '') }}"></div></div><div class="pm-info-box"><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.team_json') }}</label><textarea name="team_json" class="form-control" rows="5">{{ old('team_json', $project->team_json ?? '') }}</textarea></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.team_notes') }}</label><textarea name="team_notes" class="form-control" rows="5">{{ old('team_notes', $project->team_notes ?? '') }}</textarea></div></div></div></div>

<div class="pm-tab-panel" data-panel="technical"><div class="pm-grid pm-grid-2"><div class="pm-info-box"><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.main_url') }}</label><input type="text" name="url" class="form-control" value="{{ old('url', $project->url ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.repository_url') }}</label><input type="text" name="repository_url" class="form-control" value="{{ old('repository_url', $project->repository_url ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.documentation_url') }}</label><input type="text" name="documentation_url" class="form-control" value="{{ old('documentation_url', $project->documentation_url ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.staging_url') }}</label><input type="text" name="staging_url" class="form-control" value="{{ old('staging_url', $project->staging_url ?? '') }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.production_url') }}</label><input type="text" name="production_url" class="form-control" value="{{ old('production_url', $project->production_url ?? '') }}"></div></div><div class="pm-info-box"><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.server_notes') }}</label><textarea name="server_notes" class="form-control" rows="5">{{ old('server_notes', $project->server_notes ?? '') }}</textarea></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.deployment_notes') }}</label><textarea name="deployment_notes" class="form-control" rows="5">{{ old('deployment_notes', $project->deployment_notes ?? '') }}</textarea></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.structure_notes') }}</label><textarea name="structure_notes" class="form-control" rows="4">{{ old('structure_notes', $project->structure_notes ?? '') }}</textarea></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.documentation_notes') }}</label><textarea name="documentation_notes" class="form-control" rows="4">{{ old('documentation_notes', $project->documentation_notes ?? '') }}</textarea></div></div></div></div>

<div class="pm-tab-panel" data-panel="planning"><div class="pm-grid pm-grid-2"><div class="pm-info-box"><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.start_date') }}</label><input type="date" name="start_date" class="form-control" value="{{ old('start_date', optional($project->start_date ?? null)->format('Y-m-d')) }}"></div><div class="mb-3"><label>{{ __('project-manager::project_manager.fields.deadline') }}</label><input type="date" name="deadline" class="form-control" value="{{ old('deadline', optional($project->deadline ?? null)->format('Y-m-d')) }}"></div></div></div></div>

<div class="mt-3 d-flex gap-2">
    <a href="{{ route('project_manager.index') }}" class="btn btn-outline-primary"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
    <button type="submit" class="btn btn-outline-primary"><i class="fa-regular fa-floppy-disk" aria-hidden="true"></i></button>
</div>
