<?php

return [
    'areas' => [
        'purchase' => [
            'label' => 'Purchase',
            'department' => 'Purchase',
            'stage' => 'store-brand-manager',
            'route' => 'product_growth.store_brand_manager.dashboard',
            'icon' => 'fa-solid fa-cart-shopping',
            'summary' => 'Referencia, tipo de produto, dados de compra, fabricante, fornecedor e estrutura de combinacoes ou packs.',
            'items' => [
                'reference' => ['label' => 'Referencia / SKU', 'path' => 'reference'],
                'internal_sku' => ['label' => 'SKU interno', 'path' => 'internal_sku'],
                'ean13' => ['label' => 'EAN13', 'path' => 'ean'],
                'product_type' => ['label' => 'Tipo produto', 'path' => 'product_type'],
                'manufacturer' => ['label' => 'Manufacturer', 'path' => 'metadata.product_growth.manufacturer_name'],
                'supplier' => ['label' => 'Supplier', 'path' => 'metadata.product_growth.supplier_name'],
                'combinations' => ['label' => 'Combinacoes', 'path' => 'metadata.department_content.store-brand-manager.combinations'],
                'pack_components' => ['label' => 'Composicao pack', 'path' => 'metadata.department_content.store-brand-manager.pack_components'],
            ],
        ],
        'finance' => [
            'label' => 'Finance',
            'department' => 'Finance',
            'stage' => 'brand-compliance-manager',
            'route' => 'product_growth.brand_compliance_manager.dashboard',
            'icon' => 'fa-solid fa-file-invoice-dollar',
            'summary' => 'Regra fiscal e dados financeiros necessarios para validacao operacional do produto.',
            'items' => [
                'purchase_price_original' => ['label' => 'Compra s/ VAT fornecedor', 'path' => 'metadata.department_content.brand-compliance-manager.purchase_price_original'],
                'supplier_currency' => ['label' => 'Moeda fornecedor', 'path' => 'metadata.department_content.brand-compliance-manager.supplier_currency'],
                'currency_rate_to_eur' => ['label' => 'Taxa para EUR', 'path' => 'metadata.department_content.brand-compliance-manager.currency_rate_to_eur'],
                'purchase_price' => ['label' => 'Compra EUR sem VAT', 'path' => 'base_cost'],
                'supplier_recommended_sale_price' => ['label' => 'Venda recomendada fornecedor', 'path' => 'metadata.department_content.brand-compliance-manager.supplier_recommended_sale_price'],
                'base_sale_price' => ['label' => 'Venda EUR sem VAT', 'path' => 'base_price'],
                'desired_discount' => ['label' => 'Desconto individual', 'path' => 'metadata.department_content.brand-compliance-manager.desired_discount'],
                'tax_rule' => ['label' => 'VAT / Regra fiscal', 'path' => 'metadata.department_content.brand-compliance-manager.tax_rule'],
                'nc_code' => ['label' => 'NC code', 'path' => 'metadata.department_content.brand-compliance-manager.nc_code'],
            ],
        ],
        'sales' => [
            'label' => 'Sales',
            'department' => 'Sales',
            'stage' => 'marketing-content-manager',
            'route' => 'product_growth.marketing_content_manager.dashboard',
            'icon' => 'fa-solid fa-tags',
            'summary' => 'Caracteristicas, prioridades, canais e relacoes de venda.',
            'items' => [
                'product_characteristics' => ['label' => 'Caracteristicas do produto', 'path' => 'metadata.department_content.marketing-content-manager.characteristics'],
                'recommended_products' => ['label' => 'Produtos recomendados', 'path' => 'metadata.department_content.marketing-content-manager.recommended_products'],
                'upsell_bundles' => ['label' => 'Upsell bundles', 'path' => 'metadata.department_content.marketing-content-manager.upsell_bundles'],
            ],
        ],
        'marketing' => [
            'label' => 'Marketing',
            'department' => 'Marketing',
            'stage' => 'creative-asset-manager',
            'route' => 'product_growth.creative_asset_manager.dashboard',
            'icon' => 'fa-solid fa-bullhorn',
            'summary' => 'Foto de capa, galeria, imagens de combinacoes, videos e criativos sociais.',
            'items' => [
                'cover_image_url' => ['label' => 'Foto de capa', 'path' => 'metadata.department_content.creative-asset-manager.cover_image_url'],
                'main_image_url' => ['label' => 'Foto principal', 'path' => 'metadata.department_content.creative-asset-manager.main_image_url'],
                'gallery_urls' => ['label' => 'Fotos do produto', 'path' => 'metadata.department_content.creative-asset-manager.gallery_urls'],
                'combination_images' => ['label' => 'Fotos das combinacoes', 'path' => 'metadata.department_content.creative-asset-manager.combination_images'],
                'youtube_video_code' => ['label' => 'Codigo YouTube do video principal', 'path' => 'metadata.department_content.creative-asset-manager.youtube_video_code'],
                'social_square_url' => ['label' => 'Criativo social quadrado', 'path' => 'metadata.department_content.creative-asset-manager.social_square_url'],
                'social_story_url' => ['label' => 'Criativo story', 'path' => 'metadata.department_content.creative-asset-manager.social_story_url'],
                'social_reel_youtube_code' => ['label' => 'Codigo YouTube do video/reel social', 'path' => 'metadata.department_content.creative-asset-manager.social_reel_youtube_code'],
                'asset_notes' => ['label' => 'Notas de assets', 'path' => 'metadata.department_content.creative-asset-manager.asset_notes'],
            ],
        ],
        'logistics' => [
            'label' => 'Logistica',
            'department' => 'Logistica',
            'stage' => 'logistics-manager',
            'route' => 'product_growth.logistics_manager.dashboard',
            'icon' => 'fa-solid fa-truck-fast',
            'summary' => 'Stock, EAN fallback, peso, medidas, embalagem e restricoes de envio.',
            'items' => [
                'stock_quantity' => ['label' => 'Stock', 'path' => 'metadata.department_content.logistics-manager.stock_quantity'],
                'ean13' => ['label' => 'EAN13', 'path' => 'ean'],
                'weight' => ['label' => 'Peso', 'path' => 'weight'],
                'width' => ['label' => 'Largura', 'path' => 'width'],
                'height' => ['label' => 'Altura', 'path' => 'height'],
                'depth' => ['label' => 'Profundidade', 'path' => 'depth'],
                'package_quantity' => ['label' => 'Qtd. embalagem', 'path' => 'metadata.department_content.logistics-manager.package_quantity'],
                'measurements_verified' => ['label' => 'Medidas verificadas', 'path' => 'metadata.department_content.logistics-manager.measurements_verified'],
                'has_shipping_restrictions' => ['label' => 'Restricoes envio', 'path' => 'metadata.department_content.logistics-manager.has_shipping_restrictions'],
                'carrier_exclusions' => ['label' => 'Exclusoes transportadoras', 'path' => 'metadata.department_content.logistics-manager.carrier_exclusions'],
            ],
        ],
    ],
    'stage_area_map' => [
        'workflow-manager' => 'admin',
        'store-brand-manager' => 'purchase',
        'logistics-manager' => 'logistics',
        'brand-compliance-manager' => 'finance',
        'marketing-content-manager' => 'sales',
        'creative-asset-manager' => 'marketing',
    ],
];
