@extends('layouts.app')
@section('content')
@include('webcatalogue::Includes.css')
<div class="webcatalogue-shell">
<form id="lsg-form" method="POST" action="{{ $action }}" enctype="multipart/form-data">
@csrf
@if(($method ?? 'POST') !== 'POST') @method($method) @endif
<div class="wc-editor-layout"><div>
    <div class="wc-form-panel"><div class="wc-form-panel-head"><span class="wc-eyebrow"><i class="fa-solid fa-cube"></i> Job</span><h3>3D generation setup</h3><p class="wc-muted">Define product, provider and status. Use mock for workflow tests or Meshy API for real multi-image to 3D generation.</p></div>
        <div class="wc-studio-form-note"><i class="fa-solid fa-circle-info"></i><span>Start with product context, then add source images and final immersive outputs.</span></div><div class="wc-form-grid"><label>Store<select name="id_store" required><option value="">Select store</option>@foreach($stores as $store)<option value="{{ $store->id }}" @selected(old('id_store', $item->id_store ?? '') == $store->id)>{{ $store->name }}</option>@endforeach</select></label><label>Product<select name="id_product" required><option value="">Select product</option>@foreach($products as $product)<option value="{{ $product->id }}" @selected(old('id_product', $item->id_product ?? '') == $product->id)>#{{ $product->reference }} · {!! strip_tags($product->name) !!}</option>@endforeach</select></label><label>Provider<select name="provider"><option value="manual_upload" @selected(old('provider',$item->provider ?? '')==='manual_upload')>Manual upload</option><option value="meshy" @selected(old('provider',$item->provider ?? config('webcatalogue.3d_generation.mode'))==='meshy')>Meshy API</option><option value="tripo" @selected(old('provider',$item->provider ?? '')==='tripo') disabled>Tripo API (later)</option><option value="local_photogrammetry" @selected(old('provider',$item->provider ?? '')==='local_photogrammetry') disabled>Local photogrammetry (later)</option></select></label><label>Status<select name="status"><option value="draft" @selected(old('status',$item->status ?? '')==='draft')>Draft</option><option value="queued" @selected(old('status',$item->status ?? '')==='queued')>Queued</option><option value="processing" @selected(old('status',$item->status ?? '')==='processing')>Processing</option><option value="completed" @selected(old('status',$item->status ?? '')==='completed')>Completed</option><option value="failed" @selected(old('status',$item->status ?? '')==='failed')>Failed</option></select></label></div>
        <label>Prompt / instructions<textarea name="prompt" rows="4">{{ old('prompt', $item->prompt ?? '') }}</textarea></label><label>Notes<textarea name="notes" rows="3">{{ old('notes', $item->notes ?? '') }}</textarea></label>
    </div>
    <div class="wc-form-panel"><div class="wc-form-panel-head"><span class="wc-eyebrow"><i class="fa-solid fa-images"></i> Source images</span><h3>Input images</h3><p class="wc-muted">Upload multiple images that will be used by the future generation provider.</p></div><div class="wc-upload-zone"><i class="fa-solid fa-cloud-arrow-up"></i><strong>Drop or select source images</strong><span>Meshy accepts 1 to 4 images; use consistent lighting and front/side/back angles when possible.</span><input type="file" name="source_images[]" multiple accept="image/*"></div></div>
    <div class="wc-form-panel"><div class="wc-form-panel-head"><span class="wc-eyebrow"><i class="fa-solid fa-vr-cardboard"></i> Outputs</span><h3>3D / AR / VR files</h3><p class="wc-muted">Upload generated model and exports. These are registered as product resources.</p></div><div class="wc-output-upload-grid"><label class="wc-output-upload"><i class="fa-solid fa-cube"></i><strong>3D model</strong><span>GLB / GLTF</span><input type="file" name="result_model_3d" accept=".glb,.gltf,model/gltf-binary,model/gltf+json"></label><label class="wc-output-upload"><i class="fa-solid fa-mobile-screen"></i><strong>AR file</strong><span>USDZ / Reality / GLB</span><input type="file" name="ar_file" accept=".usdz,.reality,.glb,.gltf"></label><label class="wc-output-upload"><i class="fa-solid fa-vr-cardboard"></i><strong>VR scene</strong><span>GLB / JSON / ZIP</span><input type="file" name="vr_file" accept=".glb,.gltf,.json,.zip"></label></div></div>
</div><aside class="wc-preview-panel"><div class="wc-preview-card"><div class="wc-preview-media"><i class="fa-solid fa-wand-magic-sparkles wc-preview-icon"></i></div><div class="wc-preview-body"><h4>3D Studio workflow</h4><p class="wc-muted">Images create the source set. GLB/USDZ/VR outputs become resources attached to the product.</p></div></div></aside></div>
</form>
</div>
@endsection
