<?php

namespace Modules\DataImportWizard\Services;

use Illuminate\Support\Str;

class ImportSchemaBuilder
{
    public function __construct(
        private readonly ImportDependencyResolver $resolver
    ) {
    }

    public function build(string $rootClass): array
    {
        $graph = $this->resolver->resolve($rootClass);

        $headers = [];
        $fields = [];
        $requiredHeaders = [];
        $rules = [];
        $nodeFields = [];
        $warnings = [];

        foreach ($graph['nodes'] as $node) {
            $class = $node['class'];
            $classFields = $class::importFields();
            $classRules = $class::importRules();

            foreach ($classFields as $fieldKey => $definition) {
                $csvKey = $this->csvKeyFor($node, (string) $fieldKey);

                if (isset($fields[$csvKey])) {
                    $warnings[] = "Duplicated CSV field [{$csvKey}] generated by [{$class}].";
                    continue;
                }

                $definition = array_merge([
                    'label' => $fieldKey,
                    'required' => false,
                    'type' => 'string',
                    'example' => '',
                    'column' => $fieldKey,
                    'fillable' => true,
                    'lookup' => false,
                ], $definition);

                $definition['csv_key'] = $csvKey;
                $definition['field_key'] = (string) $fieldKey;
                $definition['source_id'] = $node['id'];
                $definition['source_alias'] = $node['alias'];
                $definition['source_class'] = $class;
                $definition['source_label'] = $node['label'];
                $definition['is_dependency'] = ! $node['is_root'];

                $headers[] = $csvKey;
                $fields[$csvKey] = $definition;
                $nodeFields[$node['id']][(string) $fieldKey] = $definition;

                $isRequired = ($definition['required'] ?? false) === true && ($node['required'] ?? true) === true;
                if ($isRequired) {
                    $requiredHeaders[] = $csvKey;
                }

                $rules[$csvKey] = $this->ruleFor($fieldKey, $definition, $classRules, $isRequired);
            }
        }

        return [
            'graph' => $graph,
            'headers' => $headers,
            'required_headers' => $requiredHeaders,
            'fields' => $fields,
            'rules' => $rules,
            'node_fields' => $nodeFields,
            'warnings' => $warnings,
        ];
    }

    public function csvKeyFor(array $node, string $fieldKey): string
    {
        if ($node['is_root'] || ($node['preserve_keys'] ?? false)) {
            return $fieldKey;
        }

        $prefix = $node['prefix'] ?: $node['alias'];

        if (Str::startsWith($fieldKey, $prefix . '_')) {
            return $fieldKey;
        }

        return $prefix . '_' . $fieldKey;
    }

    private function ruleFor(string $fieldKey, array $definition, array $classRules, bool $isRequired): array|string
    {
        if (array_key_exists($fieldKey, $classRules)) {
            return $this->adjustRequiredRule($classRules[$fieldKey], $isRequired);
        }

        $rules = [$isRequired ? 'required' : 'nullable'];

        match ($definition['type'] ?? 'string') {
            'integer', 'int' => $rules[] = 'integer',
            'decimal', 'float', 'numeric', 'money' => $rules[] = 'numeric',
            'date' => $rules[] = 'date',
            'datetime' => $rules[] = 'date',
            'email' => $rules[] = 'email',
            'boolean', 'bool' => $rules[] = 'boolean',
            default => $rules[] = 'string',
        };

        if (isset($definition['max'])) {
            $rules[] = 'max:' . $definition['max'];
        }

        return $rules;
    }

    private function adjustRequiredRule(array|string $rule, bool $isRequired): array|string
    {
        if ($isRequired) {
            return $rule;
        }

        if (is_string($rule)) {
            $parts = array_filter(explode('|', $rule), fn ($part) => $part !== 'required');
            array_unshift($parts, 'nullable');
            return implode('|', array_unique($parts));
        }

        $parts = array_values(array_filter($rule, fn ($part) => $part !== 'required'));
        array_unshift($parts, 'nullable');

        return array_values(array_unique($parts));
    }
}
